language: csharp
solution: apache-nms-amqp.sln
mono: none
dotnet: 3.0.101
script:
 - dotnet build -p:AppTargetFramework=netcoreapp3.0 -c Release
 - dotnet test ./test/Apache-NMS-AMQP-Test/Apache-NMS-AMQP-Test.csproj -f netcoreapp3.0 -c Release --filter Category!=Windows